dirList = { '/.'}; 
% '/@file_array'; ...
% '/@file_array/private'; ...
% '/@gifti'; ...
% '/@gifti/private'; ...
% '/@meeg'; ...
% '/@meeg/private'; ...
% '/@nifti'; ...
% '/@nifti/private'; ...
% '/@slover'; ...
% '/@slover/private'; ...
% '/@xmltree'; ...
% '/@xmltree/private'; ...
% '/batches'; ...
% '/canonical'; ...
% '/compat'; ...
% '/config'; ...
% '/EEGtemplates'; ...
% '/external'; ...
% '/help'; ...
% '/man'; ...
% '/matlabbatch'; ...
% '/rend'; ...
% '/spm_orthviews'; ...
% '/src'; ...
% '/tests'; ...
% '/toolbox'; ...
% '/tpm'};

addAttachedFiles(poolobj, '/Users/katherine/Downloads/spm12_linux');

% for numWorker = 1:16
%     for numFolder = 1:length(dirList)
%         loc = [workerLoc{numWorker}, dirList{numFolder}];
%         addFolderAndSubfoldersToLD_LIBRARY_PATH(loc);
%     end
% 
% end

for numWorker = 1:16
    loc = workerLoc{numWorker};
    addFolderAndSubfoldersToLD_LIBRARY_PATH(loc)
end